### ISSUE TITLE
add extra external module

### ISSUE THREAD

**Issue by millbergm** [95joaols/Lab-schoolAssignments-#43]
![Skärmbild 2021-09-28 092903](https://user-images.githubusercontent.com/71013225/135042822-42ede451-23d1-42d2-8262-c8bc022418eb.jpg)

**Comment by RikardF** [comment]
https://github.com/thebylito/react-native-navigation-bar-color

**Comment by RikardF** [comment]
Finns en tom branch skapad. #43
